// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "pigeon.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

NSObject<FlutterMessageCodec> *PigeonApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void SetUpPigeonApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PigeonApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.elevator_test.PigeonApi.startNotification"
        binaryMessenger:binaryMessenger
        codec:PigeonApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startNotificationWithError:)], @"PigeonApi api (%@) doesn't respond to @selector(startNotificationWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api startNotificationWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.elevator_test.PigeonApi.clearNotifications"
        binaryMessenger:binaryMessenger
        codec:PigeonApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(clearNotificationsWithError:)], @"PigeonApi api (%@) doesn't respond to @selector(clearNotificationsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api clearNotificationsWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.elevator_test.PigeonApi.updateCurrentFloor"
        binaryMessenger:binaryMessenger
        codec:PigeonApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(updateCurrentFloorCurrentFloor:error:)], @"PigeonApi api (%@) doesn't respond to @selector(updateCurrentFloorCurrentFloor:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSInteger arg_currentFloor = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        [api updateCurrentFloorCurrentFloor:arg_currentFloor error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
