// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by PigeonApi.
NSObject<FlutterMessageCodec> *PigeonApiGetCodec(void);

@protocol PigeonApi
- (void)startNotificationWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)clearNotificationsWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)updateCurrentFloorCurrentFloor:(NSInteger)currentFloor error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpPigeonApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PigeonApi> *_Nullable api);

NS_ASSUME_NONNULL_END
